#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module GoogleCloudStorage
  # The action to take.
  @[JSON::Serializable::Options(emit_nulls: true)]
  class BucketLifecycleRuleInnerAction
    include JSON::Serializable
    include JSON::Serializable::Unmapped

    # Optional properties

    # Target storage class. Required iff the type of the action is SetStorageClass.
    @[JSON::Field(key: "storageClass", type: String?, presence: true, ignore_serialize: storage_class.nil? && !storage_class_present?)]
    property storage_class : String?

    @[JSON::Field(ignore: true)]
    property? storage_class_present : Bool = false

    # Type of the action. Currently, only Delete and SetStorageClass are supported.
    @[JSON::Field(key: "type", type: String?, presence: true, ignore_serialize: _type.nil? && !_type_present?)]
    property _type : String?

    @[JSON::Field(ignore: true)]
    property? _type_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @storage_class : String? = nil,
      @_type : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@storage_class, @storage_class_present, @_type, @_type_present)
  end
end
