#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

module GoogleCloudStorage
  # The bucket's website configuration, controlling how the service behaves when accessing bucket contents as a web site. See the Static Website Examples for more information.
  class BucketWebsite
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # If the requested object path is missing, the service will ensure the path has a trailing '/', append this suffix, and attempt to retrieve the resulting object. This allows the creation of index.html objects to represent directory pages.
    @[JSON::Field(key: "mainPageSuffix", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter main_page_suffix : String? = nil

    # If the requested object path is missing, and any mainPageSuffix object is missing, if applicable, the service will return the named object from this bucket as the content for a 404 Not Found result.
    @[JSON::Field(key: "notFoundPage", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter not_found_page : String? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @main_page_suffix : String? = nil,
      @not_found_page : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] main_page_suffix Object to be assigned
    def main_page_suffix=(new_value : String?)
      @main_page_suffix = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] not_found_page Object to be assigned
    def not_found_page=(new_value : String?)
      @not_found_page = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@main_page_suffix, @not_found_page)
  end
end
