#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

module GoogleCloudStorage
  # The bucket's billing configuration.
  class BucketBilling
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # When set to true, Requester Pays is enabled for this bucket.
    @[JSON::Field(key: "requesterPays", type: Bool?, default: nil, required: false, nullable: false, emit_null: false)]
    getter requester_pays : Bool? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @requester_pays : Bool? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_requester_pays = @requester_pays).nil?
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_requester_pays = @requester_pays).nil?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] requester_pays Object to be assigned
    def requester_pays=(new_value : Bool?)
      unless new_value.nil?
      end

      @requester_pays = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@requester_pays)
  end
end
