#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1-SNAPSHOT
#

require "nason"
require "time"
require "log"

module GoogleCloudStorage
  # A subscription to receive Google PubSub notifications.
  class Notification
    include NASON::Serializable

    # Optional properties
    # An optional list of additional attributes to attach to each Cloud PubSub message published for this notification subscription.
    @[NASON::Field(key: "custom_attributes", type: Hash(String, String)?, nillable: true)]
    property custom_attributes : Hash(String, String)?

    # HTTP 1.1 Entity tag for this subscription notification.
    @[NASON::Field(key: "etag", type: String?, nillable: true)]
    property etag : String?

    # If present, only send notifications about listed event types. If empty, sent notifications for all event types.
    @[NASON::Field(key: "event_types", type: Array(String)?, nillable: true)]
    property event_types : Array(String)?

    # The ID of the notification.
    @[NASON::Field(key: "id", type: String?, nillable: true)]
    property id : String?

    # The kind of item this is. For notifications, this is always storage#notification.
    @[NASON::Field(key: "kind", type: String?, default: "storage#notification", nillable: true)]
    property kind : String?

    # If present, only apply this notification configuration to object names that begin with this prefix.
    @[NASON::Field(key: "object_name_prefix", type: String?, nillable: true)]
    property object_name_prefix : String?

    # The desired content of the Payload.
    @[NASON::Field(key: "payload_format", type: String?, default: "JSON_API_V1", nillable: true)]
    property payload_format : String?

    # The canonical URL of this notification.
    @[NASON::Field(key: "selfLink", type: String?, nillable: true)]
    property self_link : String?

    # The Cloud PubSub topic to which this subscription publishes. Formatted as: '//pubsub.googleapis.com/projects/{project-identifier}/topics/{my-topic}'
    @[NASON::Field(key: "topic", type: String?, nillable: true)]
    property topic : String?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(*, @custom_attributes : Hash(String, String)? = nil, @etag : String? = nil, @event_types : Array(String)? = nil, @id : String? = nil, @kind : String? = "storage#notification", @object_name_prefix : String? = nil, @payload_format : String? = "JSON_API_V1", @self_link : String? = nil, @topic : String? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.same?(o)
      self.class == o.class &&
        custom_attributes == o.custom_attributes &&
        etag == o.etag &&
        event_types == o.event_types &&
        id == o.id &&
        kind == o.kind &&
        object_name_prefix == o.object_name_prefix &&
        payload_format == o.payload_format &&
        self_link == o.self_link &&
        topic == o.topic
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [custom_attributes, etag, event_types, id, kind, object_name_prefix, payload_format, self_link, topic].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if !attributes[self.class.attribute_map[key]]? && self.class.openapi_nullable.includes?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        ({} of String => String).tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = GoogleCloudStorage.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {} of String => String
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.includes?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        ({} of String => String).tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
