#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module GoogleCloudStorage
  # A rewrite response.
  @[JSON::Serializable::Options(emit_nulls: true)]
  class RewriteResponse
    include JSON::Serializable
    include JSON::Serializable::Unmapped

    # Optional properties
    # true if the copy is finished; otherwise, false if the copy is in progress. This property is always present in the response.
    @[JSON::Field(key: "done", type: Bool?, presence: true, ignore_serialize: done.nil? && !done_present?)]
    property done : Bool?

    @[JSON::Field(ignore: true)]
    property? done_present : Bool = false

    # The kind of item this is.
    @[JSON::Field(key: "kind", type: String?, default: "storage#rewriteResponse", presence: true, ignore_serialize: kind.nil? && !kind_present?)]
    property kind : String?

    @[JSON::Field(ignore: true)]
    property? kind_present : Bool = false

    # The total size of the object being copied in bytes. This property is always present in the response.
    @[JSON::Field(key: "objectSize", type: String?, presence: true, ignore_serialize: object_size.nil? && !object_size_present?)]
    property object_size : String?

    @[JSON::Field(ignore: true)]
    property? object_size_present : Bool = false

    @[JSON::Field(key: "resource", type: Object?, presence: true, ignore_serialize: resource.nil? && !resource_present?)]
    property resource : Object?

    @[JSON::Field(ignore: true)]
    property? resource_present : Bool = false

    # A token to use in subsequent requests to continue copying data. This token is present in the response only when there is more data to copy.
    @[JSON::Field(key: "rewriteToken", type: String?, presence: true, ignore_serialize: rewrite_token.nil? && !rewrite_token_present?)]
    property rewrite_token : String?

    @[JSON::Field(ignore: true)]
    property? rewrite_token_present : Bool = false

    # The total bytes written so far, which can be used to provide a waiting user with a progress indicator. This property is always present in the response.
    @[JSON::Field(key: "totalBytesRewritten", type: String?, presence: true, ignore_serialize: total_bytes_rewritten.nil? && !total_bytes_rewritten_present?)]
    property total_bytes_rewritten : String?

    @[JSON::Field(ignore: true)]
    property? total_bytes_rewritten_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(*, @done : Bool? = nil, @kind : String? = "storage#rewriteResponse", @object_size : String? = nil, @resource : Object? = nil, @rewrite_token : String? = nil, @total_bytes_rewritten : String? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.same?(o)
      self.class == o.class &&
        done == o.done &&
        kind == o.kind &&
        object_size == o.object_size &&
        resource == o.resource &&
        rewrite_token == o.rewrite_token &&
        total_bytes_rewritten == o.total_bytes_rewritten
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [UInt64] Hash code
    def_hash(@done, @kind, @object_size, @resource, @rewrite_token, @total_bytes_rewritten)
  end
end
