tasks:
  - name: "Update api files"
    file_glob: './src/google_cloud_storage/api/*.cr'
    changes:
      -
        name: 'Remove common method prefix "storage_[api_name]_"'
        pattern: 'storage_%{api_name}_'
        new_value: ''
      -
        name: 'Restore operation name'
        pattern: 'operation: "%{capitalized_api_name}Api.'
        new_value: 'operation: "%{capitalized_api_name}Api.storage_%{api_name}_'
  - name: "Update objects api"
    file_glob: './src/google_cloud_storage/api/objects_api.cr'
    changes:
      -
        name: "Update ::File to IO | String"
        pattern: ': ::File'
        new_value: ': IO | String'
