#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::BucketBilling
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::BucketBilling do
  describe "test an instance of BucketBilling" do
    it "should create an instance of BucketBilling" do
      # instance = GoogleCloudStorage::BucketBilling.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::BucketBilling)
    end
  end

  describe "test attribute 'requester_pays'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
