#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1-SNAPSHOT
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::BucketCustomPlacementConfig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::BucketCustomPlacementConfig do
  describe "test an instance of BucketCustomPlacementConfig" do
    it "should create an instance of BucketCustomPlacementConfig" do
      # instance = GoogleCloudStorage::BucketCustomPlacementConfig.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::BucketCustomPlacementConfig)
    end
  end

  describe "test attribute 'data_locations'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
