#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::BucketEncryption
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::BucketEncryption do
  describe "test an instance of BucketEncryption" do
    it "should create an instance of BucketEncryption" do
      # instance = GoogleCloudStorage::BucketEncryption.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::BucketEncryption)
    end
  end

  describe "test attribute 'default_kms_key_name'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
