#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1-SNAPSHOT
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::BucketAutoclass
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::BucketAutoclass do
  describe "test an instance of BucketAutoclass" do
    it "should create an instance of BucketAutoclass" do
      # instance = GoogleCloudStorage::BucketAutoclass.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::BucketAutoclass)
    end
  end

  describe "test attribute 'enabled'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'toggle_time'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
