#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::BucketLifecycle
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::BucketLifecycle do
  describe "test an instance of BucketLifecycle" do
    it "should create an instance of BucketLifecycle" do
      # instance = GoogleCloudStorage::BucketLifecycle.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::BucketLifecycle)
    end
  end

  describe "test attribute 'rule'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
