#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::BucketLifecycleRuleInnerAction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::BucketLifecycleRuleInnerAction do
  describe "test an instance of BucketLifecycleRuleInnerAction" do
    it "should create an instance of BucketLifecycleRuleInnerAction" do
      # instance = GoogleCloudStorage::BucketLifecycleRuleInnerAction.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::BucketLifecycleRuleInnerAction)
    end
  end

  describe "test attribute 'storage_class'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
