#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1-SNAPSHOT
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::BucketRetentionPolicy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::BucketRetentionPolicy do
  describe "test an instance of BucketRetentionPolicy" do
    it "should create an instance of BucketRetentionPolicy" do
      # instance = GoogleCloudStorage::BucketRetentionPolicy.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::BucketRetentionPolicy)
    end
  end

  describe "test attribute 'effective_time'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'is_locked'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'retention_period'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
