#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::ComposeRequestObjectPreconditions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::ComposeRequestObjectPreconditions do
  describe "test an instance of ComposeRequestObjectPreconditions" do
    it "should create an instance of ComposeRequestObjectPreconditions" do
      # instance = GoogleCloudStorage::ComposeRequestObjectPreconditions.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::ComposeRequestObjectPreconditions)
    end
  end

  describe "test attribute 'if_generation_match'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
