#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1-SNAPSHOT
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::ObjectOwner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::ObjectOwner do
  describe "test an instance of ObjectOwner" do
    it "should create an instance of ObjectOwner" do
      # instance = GoogleCloudStorage::ObjectOwner.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::ObjectOwner)
    end
  end

  describe "test attribute 'entity'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'entity_id'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
