#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::ObjectCustomerEncryption
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::ObjectCustomerEncryption do
  describe "test an instance of ObjectCustomerEncryption" do
    it "should create an instance of ObjectCustomerEncryption" do
      # instance = GoogleCloudStorage::ObjectCustomerEncryption.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::ObjectCustomerEncryption)
    end
  end

  describe "test attribute 'encryption_algorithm'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'key_sha256'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
