#  Cloud Storage JSON API
#
# Stores and retrieves potentially large, immutable data objects.
#
# The version of the OpenAPI document: v1
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleCloudStorage::PolicyBindingsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleCloudStorage::PolicyBindingsInner do
  describe "test an instance of PolicyBindingsInner" do
    it "should create an instance of PolicyBindingsInner" do
      # instance = GoogleCloudStorage::PolicyBindingsInner.new
      # expect(instance).to be_instance_of(GoogleCloudStorage::PolicyBindingsInner)
    end
  end

  describe "test attribute 'condition'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'members'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'role'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
